
#ifndef LITHA_H
#define LITHA_H

#include "IThruster.h"
#include "IRotationController.h"
#include "IPositionController.h"
#include "ILinearThrustRotationController.h"
#include "ILinearThruster.h"
#include "IController.h"
#include "ICollisionMaterial.h"
#include "IAngularThruster.h"
#include "IWorld.h"
#include "IDynamicBody.h"
#include "IEngine.h"
#include "IBody.h"
#include "ICharacter.h"
#include "ICollisionGeometry.h"
#include "IInputProfile.h"
#include "IMesh.h"
#include "IMeshCollisionGeometry.h"
#include "IBoxCollisionGeometry.h"
#include "ISphereCollisionGeometry.h"
#include "IPhysics.h"
#include "IStaticBody.h"
#include "IThirdPersonCameraController.h"
#include "IWantInput.h"
#include "ICharacterController.h"
#include "IShader.h"
#include "IPostProcessingChain.h"
#include "ITransformable.h"
#include "IProxyTransformable.h"
#include "INodeHandler.h"
#include "IUpdatable.h"
#include "ICamera.h"
#include "IMotionSensor.h"
#include "ISoundSystem.h"
#include "ISound2D.h"
#include "ISound3D.h"
#include "IRenderSystem.h"
#include "IWantEvents.h"
#include "ISoundSource.h"
#include "IEventQueue.h"

#include "ICameraCollider.h"
#include "IThirdPersonCameraCollider.h"

#include "IBobAnimator.h"

#include "Event.h"
#include "Buttons.h"
#include "CollisionMaterialInteraction.h"

#endif

