// Written by Michael Zeilfelder, please check licenseHCraft.txt for the zlib-style license text.

#ifndef GUI_IDS_H
#define GUI_IDS_H

enum GUI_IDS
{
    // menue
    GUI_OPEN_MODEL_FILE= 100,
    GUI_LOAD_LEVEL,
    GUI_QUIT,
    GUI_TOGGLE_PHYSICS_DEBUG,
    GUI_SAVE_SETTINGS,
    GUI_LOAD_SETTINGS,
    GUI_OPEN_USER_CONTROLS,
    GUI_FILEDLG_OPEN_MODEL,
    GUI_OPEN_GUI_DLG,
    GUI_FILEDLG_OPEN_GUI,
    GUI_MENU,

    // recorder
    GUI_SAVE_LAST_RECORDING,
    GUI_TOGGLE_AUTOSAVE_RECORDING,
    GUI_TOGGLE_AUTOLOAD_RECORDING,

    // intro
    GUI_IMG_INTRO,

    // icons
    GUI_ICON_OPEN_FILE,
    GUI_ICON_TOOLBAR,
    GUI_ICON_ABOUT,

    // windows
    GUI_TOOLBOX,
    GUI_TAB_TOOLBOX,
    GUI_CONTROLLER_DISPLAY,
    GUI_WND_USER_CONTROLS,
    GUI_WND_EDITOR,

    // steering settings
    EDIT_ROTATION_SPEED,
    EDIT_SCALE_ROTATION_SPEED,
    EDIT_SCALE_ROTATION_ENGINE,
    EDIT_FORCE_FACTOR,
    EDIT_BRAKE_FACTOR,
    EDIT_SCALE_ROLLING,
    EDIT_MAX_ROLLING,
    EDIT_SCALE_PITCH_FLYING,
    EDIT_SCALE_ALIGNMENT,
    BTN_SET_STEERING,

    // camera settings
    LIST_CAMERAS,
    EDIT_CAM_BEHIND,
    EDIT_CAM_HEIGHT,
    EDIT_CAM_UPWARDS,
    EDIT_CAM_DOWNWARDS,
    EDIT_CAM_TARGET_FRONT,
    EDIT_CAM_TRAILING,
    EDIT_CAM_SPEED_FACTOR_SLOW,
    EDIT_CAM_SPEED_FACTOR_FAST,
    BTN_SET_CAMERA,

    // physics settings
    EDIT_PHYSICS_TIMESTEP,
    EDIT_PHYSICS_ROLLFRICTION,
    EDIT_PHYSICS_AIRCONST,
    EDIT_PHYSICS_GRAVITY,
    EDIT_PHYSICS_HOVER_MASS,
    EDIT_PHYSICS_HOVER_MAX_SPEED,
    BTN_SET_PHYSICS,

    // device settings
    SCROLL_MOUSE_MAX_CHANGE,
    SCROLL_JS_DEAD_AREA,
    SCROLL_JS_DEAD_AREA_LAST = SCROLL_JS_DEAD_AREA + 4,
    SCROLL_JS_MAX_AREA,
    SCROLL_JS_MAX_AREA_LAST = SCROLL_JS_MAX_AREA + 4,
    BTN_CALIBRATE_JOYSTICK,
    BTN_CALIBRATE_JOYSTICK_LAST = BTN_CALIBRATE_JOYSTICK + 4,

    // levelmanager
    GUI_WND_LEVEL_SELECTION,
    GUI_LIST_LEVELS,

    // modellist
    GUI_WND_MODEL_LIST,
    GUI_LIST_MODELS,

    // editor
    BTN_NODES,
    BTN_PLAYER_START,
    BTN_TRACK_MARKER,
    BTN_TELEPORT_SOURCE,
    BTN_TELEPORT_TARGET,
    BTN_FINISH_LINE,
    BTN_SOUNDS,
    BTN_AI,
    BTN_OBJECTS,
    BTN_SAVE_LEVEL,
    WND_PLAYER_START,
    WND_TRACK_MARKER,
    WND_TELEPORT_SOURCE,
    WND_TELEPORT_TARGET,
    WND_FINISH_LINE,
    WND_SOUNDS,
    WND_AI,
    WND_OBJECTS,
    WND_NODE_MANAGER,

    // editor - levelstarts
    LIST_LEVEL_STARTS,
    BTN_GO_LEVEL_START,
    CHECKBOX_SET_LEVEL_START,

    // editor track markers
    LIST_TRACKMARKERS,
    BTN_GO_TRACKMARKER,
    BTN_REMOVE_TRACKMARKER,
    BTN_AUTO_ALIGN,
    BTN_ROTATE_180,
    BTN_LEFT_ADD,
    BTN_LEFT_SUB,
    BTN_RIGHT_ADD,
    BTN_RIGHT_SUB,
    BTN_TOP_ADD,
    BTN_TOP_SUB,
    BTN_BOTTOM_ADD,
    BTN_BOTTOM_SUB,
    STATIC_LEFT,
    STATIC_RIGHT,
    STATIC_TOP,
    STATIC_BOTTOM,
    CHECKBOX_SET_TRACKMARKER,
    CHECKBOX_INSERT_TRACKMARKER,
    CHECKBOX_APPEND_TRACKMARKER,
    CHECKBOX_WALL_LEFT,
    CHECKBOX_WALL_RIGHT,
    CHECKBOX_WALL_TOP,
    CHECKBOX_WALL_BOTTOM,
    CHECKBOX_DEFAULT_SIZE,
    CHECKBOX_RELOCATE,

    // editor - finish line
    STATIC_FINISH_LINE,
    BTN_GO_FINISH_LINE,
    CHECKBOX_SET_FINISH_LINE,

    // editor - teleports
    STATIC_TP_START,
    BTN_GO_TP_START,
    CHECKBOX_SET_TP_START,
    STATIC_TP_TARGET,
    BTN_GO_TP_TARGET,
    CHECKBOX_SET_TP_TARGET,

    // editor - model objects
    LIST_LEVELMODELS,
    BTN_GO_LEVELMODEL,
    BTN_ADD_LEVELMODEL,
    BTN_REMOVE_LEVELMODEL,
    CHECKBOX_SET_LEVELMODEL,
    FILEDLG_OPEN_LEVELMODEL,
    BTN_POS_X_ADD,
    BTN_POS_X_SUB,
    EDIT_POS_X,
    BTN_POS_Y_ADD,
    BTN_POS_Y_SUB,
    EDIT_POS_Y,
    BTN_POS_Z_ADD,
    BTN_POS_Z_SUB,
    EDIT_POS_Z,
    BTN_ROT_X_ADD,
    BTN_ROT_X_SUB,
    EDIT_ROT_X,
    BTN_ROT_Y_ADD,
    BTN_ROT_Y_SUB,
    EDIT_ROT_Y,
    BTN_ROT_Z_ADD,
    BTN_ROT_Z_SUB,
    EDIT_ROT_Z,
    SPIN_MODEL_AMB_R,
    SPIN_MODEL_AMB_G,
    SPIN_MODEL_AMB_B,

    // nodemanager
    BTN_LOAD_NODEMANAGER,
    BTN_SAVE_NODEMANAGER,
    FILEDLG_OPEN_MESH,
    FILEDLG_OPEN_ANI_MESH,
    STATIC_MODELS,
    LIST_MODELS,
    BTN_OPEN_NODES,
    STATIC_NODES,
    LIST_NODES,
    BTN_NODE_ADD_EMPTY,
    BTN_NODE_ADD_MESH,
    BTN_NODE_ADD_ANIM_MESH,
    BTN_NODE_ADD_LIGHT,
    BTN_NODE_REMOVE,
    BTN_OPEN_MODEL,

    EDIT_NODE_NAME,

    STATIC_NODE_EDIT,
    STATIC_NODE_FILE,
    SPIN_NODE_POS_X,
    SPIN_NODE_POS_Y,
    SPIN_NODE_POS_Z,
    SPIN_NODE_ROT_X,
    SPIN_NODE_ROT_Y,
    SPIN_NODE_ROT_Z,
    SPIN_NODE_SCALE_X,
    SPIN_NODE_SCALE_Y,
    SPIN_NODE_SCALE_Z,
    CHECKBOX_NODE_BF_CULLING,

    SPIN_ANIM_SPEED,

    CHECKBOX_NODE_CAST_SHADOWS,
    SPIN_NODE_RADIUS,
    SPIN_NODE_DIF_R,
    SPIN_NODE_DIF_G,
    SPIN_NODE_DIF_B,
    SPIN_NODE_DIF_A,
    SPIN_NODE_SPC_R,
    SPIN_NODE_SPC_G,
    SPIN_NODE_SPC_B,
    SPIN_NODE_SPC_A,

    GUI_MAX_ID,
};

#endif // GUI_EVENTS_H
