# Horde3D SDK

all:
	#
	#
	#
	# Building Horde3D Engine
	#
	cd Source/Horde3D\ Engine; make CFLAGS="${CFLAGS}"
	#
	#
	#
	# Building Horde3D Utils
	#
	cd Source/Horde3D\ Utils; make CFLAGS="${CFLAGS}"
	#
	#
	#
	# Building Collada Converter
	#
	cd Source/Collada\ Converter; make CFLAGS="${CFLAGS}"
	#
	#
	#
	# Building Sample Chicago
	#
	cd Samples/Chicago; make CFLAGS="${CFLAGS}"
	#
	#
	#
	# Building Sample Knight
	#
	cd Samples/Knight; make CFLAGS="${CFLAGS}"
	#
	#
	#


clean:
	cd Source/Horde3D\ Engine; make clean
	cd Source/Horde3D\ Utils; make clean
	cd Source/Collada\ Converter; make clean
	cd Samples/Chicago; make clean
	cd Samples/Knight; make clean
