cvirrcamcontroller:
	g++ -o test test.cpp CvIrrCamController.cpp -lIrrlicht -lcv -lhighgui -lGL -lGLU -lm -lXxf86vm -lpng -ljpeg
cvirrcamtexture:
	gcc -o test_camtexture test_camtexture.cpp CvIrrCamTexture.cpp -lIrrlicht -lcv -lhighgui -lGL -lGLU -lm -lXxf86vm  -lpng -ljpeg
cvirravitexture:
	gcc -o test_avitexture test_avitexture.cpp CvIrrAviTexture.cpp -lIrrlicht -lcv -lhighgui -lGL -lGLU -lm -lXxf86vm -lpng -ljpeg
cvirrrenderavi:
	gcc -o test_renderavi test_renderavi.cpp CvIrrRenderAvi.cpp -lIrrlicht -lcv -lhighgui -lGL -lGLU -lm -lXxf86vm -lpng -ljpeg
zip:
	tar -cjvf CvIrrCamController-0.x.tar.bz2 CvIrrCamController/*