CPP = g++
OPTIMIZE = -O3
OPTS = -I"/home/Dev/lib/Irrlicht/include" -I"/usr/X11R6/include" -L"/usr/X11R6/lib" -L"/home/Dev/lib/Irrlicht/lib/Linux"  -I"/usr/X11R6/include" -L"/usr/X11R6/lib" -lIrrlicht -lGL -lGLU -lXxf86vm -lXext -
all:
        $(CPP) main.cpp -o game $(OPTIMIZE) $(INCLUDE) $(OPTS)
