// zur Verhinderung doppelter Definition
#ifndef GUI_H
#define GUI_H

#include <irrlicht.h>
#include "CGUIFileOpenDialog_Modified.h"

// Namespace DunGen : DungeonGenerator
namespace DunGen
{
	// Vorabdeklaration
	class COptionen;

	// ID's der GUI-Elemente
	enum
	{
		// Fenster
        _GUI_ID_WINDOW_DATEIZUGRIFF_EINSTELLUNGEN_  = 0x10000,
		_GUI_ID_WINDOW_DATEIZUGRIFF_ERGEBNISSE_,
		_GUI_ID_WINDOW_FRAKTALEDITOR_,
		_GUI_ID_WINDOW_VOXELRAUM_,
		_GUI_ID_WINDOW_GAENGE_,
		_GUI_ID_WINDOW_ARCHITEKT_,
		_GUI_ID_WINDOW_ERSTELLUNG_,
		_GUI_ID_WINDOW_WEITERES_,

		// Toolbar
		_GUI_ID_BUTTON_DATEIZUGRIFF_EINSTELLUNGEN_,
		_GUI_ID_BUTTON_DATEIZUGRIFF_ERGEBNISSE_,
		_GUI_ID_BUTTON_FRAKTALEDITOR_,
		_GUI_ID_BUTTON_VOXELHOEHLE_,
		_GUI_ID_BUTTON_GAENGE_,
		_GUI_ID_BUTTON_ARCHITEKT_,
		_GUI_ID_BUTTON_ERSTELLUNG_,
		_GUI_ID_BUTTON_WEITERES_,

		// Dateizugriff: Einstellungen
		_GUI_ID_CHECKBOX_DATEI_EINSTELLUNGEN_FRAKTALPARAMETER_,
		_GUI_ID_CHECKBOX_DATEI_EINSTELLUNGEN_WEITERE_FRAKTALEINSTELLUNGEN_,
		_GUI_ID_CHECKBOX_DATEI_EINSTELLUNGEN_VOXELRAUM_,
		_GUI_ID_CHECKBOX_DATEI_EINSTELLUNGEN_GAENGE_,
		_GUI_ID_CHECKBOX_DATEI_EINSTELLUNGEN_DETAILOBJEKTE_,
		_GUI_ID_CHECKBOX_DATEI_EINSTELLUNGEN_ARCHITEKT_,
		_GUI_ID_CHECKBOX_DATEI_EINSTELLUNGEN_SUBSZENEN_,
		_GUI_ID_CHECKBOX_DATEI_EINSTELLUNGEN_ERSTELLUNG_,
		_GUI_ID_CHECKBOX_DATEI_EINSTELLUNGEN_WEITERES_,

		_GUI_ID_BUTTON_SPEICHERN_EINSTELLUNGEN_,
		_GUI_ID_BUTTON_LADEN_EINSTELLUNGEN_,

		_GUI_ID_FILEOPENDIALOG_SPEICHERN_EINSTELLUNGEN_,
		_GUI_ID_FILEOPENDIALOG_LADEN_EINSTELLUNGEN_,

		// Dateizugriff: Ergebnisse
		_GUI_ID_BUTTON_SPEICHERN_ERGEBNISSE_FRAKTALSTRINGS_,
		_GUI_ID_BUTTON_SPEICHERN_ERGEBNISSE_DICHTE_XY_,
		_GUI_ID_BUTTON_SPEICHERN_ERGEBNISSE_DICHTE_XZ_,
		_GUI_ID_BUTTON_SPEICHERN_ERGEBNISSE_DICHTE_YZ_,
		_GUI_ID_BUTTON_SPEICHERN_ERGEBNISSE_DREIECKSMESH_,
		_GUI_ID_BUTTON_SPEICHERN_ERGEBNISSE_DUNGEON_,
		_GUI_ID_BUTTON_LADEN_ERGEBNISSE_DUNGEON_,

		_GUI_ID_FILEOPENDIALOG_SPEICHERN_ERGEBNISSE_FRAKTALSTRINGS_,
		_GUI_ID_FILEOPENDIALOG_SPEICHERN_ERGEBNISSE_DICHTE_XY_,
		_GUI_ID_FILEOPENDIALOG_SPEICHERN_ERGEBNISSE_DICHTE_XZ_,
		_GUI_ID_FILEOPENDIALOG_SPEICHERN_ERGEBNISSE_DICHTE_YZ_,
		_GUI_ID_FILEOPENDIALOG_SPEICHERN_ERGEBNISSE_DREIECKSMESH_HOEHLE_,
		_GUI_ID_FILEOPENDIALOG_SPEICHERN_ERGEBNISSE_DUNGEON_,
		_GUI_ID_FILEOPENDIALOG_LADEN_ERGEBNISSE_DUNGEON_,
		
		// Fraktaleditor
		_GUI_ID_EDITBOX_WINKELGIER_WERT_,
		_GUI_ID_EDITBOX_WINKELGIER_MIN_,
		_GUI_ID_EDITBOX_WINKELGIER_MAX_,
		_GUI_ID_EDITBOX_WINKELGIER_KOMMASTELLEN_,

		_GUI_ID_EDITBOX_WINKELNICK_WERT_,
		_GUI_ID_EDITBOX_WINKELNICK_MIN_,
		_GUI_ID_EDITBOX_WINKELNICK_MAX_,
		_GUI_ID_EDITBOX_WINKELNICK_KOMMASTELLEN_,

		_GUI_ID_EDITBOX_WINKELROLL_WERT_,
		_GUI_ID_EDITBOX_WINKELROLL_MIN_,
		_GUI_ID_EDITBOX_WINKELROLL_MAX_,
		_GUI_ID_EDITBOX_WINKELROLL_KOMMASTELLEN_,

		_GUI_ID_EDITBOX_RADIUSSTART_WERT_,
		_GUI_ID_EDITBOX_RADIUSSTART_MIN_,
		_GUI_ID_EDITBOX_RADIUSSTART_MAX_,
		_GUI_ID_EDITBOX_RADIUSSTART_KOMMASTELLEN_,

		_GUI_ID_EDITBOX_RADIUSFAKTOR_WERT_,
		_GUI_ID_EDITBOX_RADIUSFAKTOR_MIN_,
		_GUI_ID_EDITBOX_RADIUSFAKTOR_MAX_,
		_GUI_ID_EDITBOX_RADIUSFAKTOR_KOMMASTELLEN_,

		_GUI_ID_EDITBOX_RADIUSDEKREMENTOR_WERT_,
		_GUI_ID_EDITBOX_RADIUSDEKREMENTOR_MIN_,
		_GUI_ID_EDITBOX_RADIUSDEKREMENTOR_MAX_,
		_GUI_ID_EDITBOX_RADIUSDEKREMENTOR_KOMMASTELLEN_,

		_GUI_ID_EDITBOX_STARTSTRING_,
		_GUI_ID_EDITBOX_STARTSTRING_ERLAUBTE_SYMBOLE_,
		_GUI_ID_EDITBOX_STARTSTRING_MINLAENGE_,
		_GUI_ID_EDITBOX_STARTSTRING_MAXLAENGE_,

		_GUI_ID_EDITBOX_SYMBOL_,
		_GUI_ID_EDITBOX_SYMBOLERSETZUNG_,
		_GUI_ID_EDITBOX_SYMBOLERSETZUNG_ERLAUBTE_SYMBOLE_,
		_GUI_ID_EDITBOX_SYMBOLERSETZUNG_MINLAENGE_,
		_GUI_ID_EDITBOX_SYMBOLERSETZUNG_MAXLAENGE_,

		_GUI_ID_EDITBOX_ERSETZUNGSINFO_,
		_GUI_ID_EDITBOX_ITERATIONSSTUFE_,

		_GUI_ID_LISTBOX_ERSETZUNGSREGELN_,

		_GUI_ID_BUTTON_ZUFALLSPARAMETER_,
		_GUI_ID_BUTTON_ZUFALLSSTART_,
		_GUI_ID_BUTTON_ZUFALLSREGEL_,
		_GUI_ID_BUTTON_REGELHINZUFUEGEN_,
		_GUI_ID_BUTTON_REGELNLOESCHEN_,
		_GUI_ID_BUTTON_FRAKTALGENERIEREN_,
		_GUI_ID_BUTTON_ZUFALLSFRAKTALGENERIEREN_,

		// Voxelraum
        _GUI_ID_EDITBOX_RAND_,
		_GUI_ID_EDITBOX_MINIMALRADIUS_,		
		_GUI_ID_EDITBOX_EROSION_ZUFALLSSEED_,
		_GUI_ID_EDITBOX_EROSIONSWAHRSCHEINLICHKEIT_,
		_GUI_ID_EDITBOX_VERTICES_VERWACKLUNGSTAERKE_,
		_GUI_ID_EDITBOX_VERWACKLUNG_ZUFALLSSEED_,
		_GUI_ID_EDITBOX_VERWACKLUNG_ZUFALLSPARAMETER_A_,
		_GUI_ID_EDITBOX_VERWACKLUNG_ZUFALLSPARAMETER_C_,
		_GUI_ID_EDITBOX_VERWACKLUNG_ZUFALLSPARAMETER_M_,
		_GUI_ID_EDITBOX_DETAILSTUFEN_VOXELMESH_,
		
		_GUI_ID_LISTBOX_EROSIONSSCHRITTE_,
		
		_GUI_ID_CHECKBOX_SCHWEBENDE_FRAGMENTE_ENTFERNEN_,
		_GUI_ID_CHECKBOX_EROSION_VORGEGEBENEN_RANDSEED_BENUTZEN_,	
		_GUI_ID_CHECKBOX_VERTICES_VERWACKELN_,
		_GUI_ID_CHECKBOX_MESH_GLAETTEN_,

		_GUI_ID_COMBOBOX_NORMALEN_BERECHNUNGSMETHODE_,

		_GUI_ID_BUTTON_EROSIONSSCHRITT_HINZUFUEGEN_,
		_GUI_ID_BUTTON_EROSIONSSCHRITTE_LOESCHEN_,
		_GUI_ID_BUTTON_VOXEL_BERECHNEN_,
		_GUI_ID_BUTTON_ZEIGE_DICHTE_XY_,
		_GUI_ID_BUTTON_ZEIGE_DICHTE_XZ_,
		_GUI_ID_BUTTON_ZEIGE_DICHTE_YZ_,
		_GUI_ID_BUTTON_VOXEL_ZU_DREIECKSNETZ_BERECHNEN_,
		_GUI_ID_BUTTON_ZEIGE_DRAHTGITTERMODELL_,

		// Gaenge
		_GUI_ID_EDITBOX_GANGBREITE_,
		_GUI_ID_EDITBOX_PUNKT_X_,
		_GUI_ID_EDITBOX_PUNKT_Y_,
		_GUI_ID_EDITBOX_PUNKT_TEXTUREX_,
		_GUI_ID_EDITBOX_PUNKTABSTAND_,
		_GUI_ID_EDITBOX_TEXTUREY_ERHOEHUNG_,
		_GUI_ID_EDITBOX_DETAILSTUFEN_GANGMESH_,
		_GUI_ID_EDITBOX_GANGTEXTUR_,

		_GUI_ID_LISTBOX_GANGPUNKTE_,

		_GUI_ID_BUTTON_NEU_GANGPUNKT_,
		_GUI_ID_BUTTON_UEBERNEHMEN_GANGPUNKT_,
		_GUI_ID_BUTTON_LOESCHEN_GANGPUNKT_,
		_GUI_ID_BUTTON_DATEI_WAEHLEN_GANGTEXTUR_,

		_GUI_ID_FILEOPENDIALOG_GANGTEXTUR_,
				
		// Gaenge: Detailobjekte
		_GUI_ID_EDITBOX_DETAILOBJEKT_BENENNUNG_,
		_GUI_ID_EDITBOX_DETAILOBJEKT_SKALIERUNG_X_,
		_GUI_ID_EDITBOX_DETAILOBJEKT_SKALIERUNG_Y_,
		_GUI_ID_EDITBOX_DETAILOBJEKT_SKALIERUNG_Z_,
		_GUI_ID_EDITBOX_DETAILOBJEKT_ROTATION_X_,
		_GUI_ID_EDITBOX_DETAILOBJEKT_ROTATION_Y_,
		_GUI_ID_EDITBOX_DETAILOBJEKT_ROTATION_Z_,
		_GUI_ID_EDITBOX_DETAILOBJEKT_POSITION_X_,
		_GUI_ID_EDITBOX_DETAILOBJEKT_POSITION_Y_,
		_GUI_ID_EDITBOX_DETAILOBJEKT_ABTASTUNG_,
		_GUI_ID_EDITBOX_DETAILOBJEKT_FAKTOR_NUMABSTAND_,
		_GUI_ID_EDITBOX_DETAILOBJEKT_NUMABSTAND_MIN_,
		_GUI_ID_EDITBOX_DETAILOBJEKT_NUMABSTAND_MAX_,
		_GUI_ID_EDITBOX_DETAILOBJEKT_NUMABSTAND_MIN_ANFANG_,
		_GUI_ID_EDITBOX_DETAILOBJEKT_NUMABSTAND_MAX_ANFANG_,
		_GUI_ID_EDITBOX_DETAILOBJEKT_PFADINFO_,

		_GUI_ID_LISTBOX_DETAILOBJEKTE_,

		_GUI_ID_CHECKBOX_OBJEKT_GANGENDE_,
		
		_GUI_ID_BUTTON_NEU_DETAILOBJEKT_,
		_GUI_ID_BUTTON_UEBERNEHMEN_DETAILOBJEKT_,
		_GUI_ID_BUTTON_LOESCHEN_DETAILOBJEKT_,

		_GUI_ID_FILEOPENDIALOG_DETAILOBJEKTMESH_,

		// Architekt
		_GUI_ID_EDITBOX_ARCHITEKT_KONTRUKTIONS_ZUFALLSSEED_,
		_GUI_ID_EDITBOX_ARCHITEKT_RAUMSEKTORAUSDEHNUNG_,
		_GUI_ID_EDITBOX_ARCHITEKT_MINABSTAND_RAUM_HOEHLE_,
		_GUI_ID_EDITBOX_ARCHITEKT_ABSTAND_BODEN_,
		_GUI_ID_EDITBOX_ARCHITEKT_ABSTANDSTEST_TIEFE_,
		_GUI_ID_EDITBOX_ARCHITEKT_AUSFRAESTIEFE_,
		_GUI_ID_EDITBOX_ARCHITEKT_SICHERHEITSABSTAND_,

		_GUI_ID_EDITBOX_ARCHITEKT_WAHRSCHEINLICHKEIT_ZUSATZGANG_HOEHLE_,
		_GUI_ID_EDITBOX_ARCHITEKT_WAHRSCHEINLICHKEIT_ZUSATZGANG_RAUM_,
		_GUI_ID_EDITBOX_ARCHITEKT_WAHRSCHEINLICHKEIT_LEERERRAUM_HOEHLE_,
		_GUI_ID_EDITBOX_ARCHITEKT_WAHRSCHEINLICHKEIT_LEERERRAUM_RAUM_,

		_GUI_ID_CHECKBOX_ARCHITEKT_VORGEGEBENEN_ZUFALLSSEED_NUTZEN_,

		// Architekt: Subszenen
		_GUI_ID_EDITBOX_SUBSZENE_BENENNUNG_,
		_GUI_ID_EDITBOX_SUBSZENE_SKALIERUNG_X_,
		_GUI_ID_EDITBOX_SUBSZENE_SKALIERUNG_Y_,
		_GUI_ID_EDITBOX_SUBSZENE_SKALIERUNG_Z_,
		_GUI_ID_EDITBOX_SUBSZENE_WAHRSCHEINLICHKEIT_HOEHLE_,
		_GUI_ID_EDITBOX_SUBSZENE_WAHRSCHEINLICHKEIT_RAUM_,
		_GUI_ID_EDITBOX_SUBSZENE_GANGSPLINEABLEITUNG_RAUM_RAUM_,
		_GUI_ID_EDITBOX_SUBSZENE_GANGSPLINEABLEITUNG_RAUM_HOEHLE_,
		_GUI_ID_EDITBOX_SUBSZENE_GANGSPLINEABLEITUNG_HOEHLE_RAUM_,
		_GUI_ID_EDITBOX_SUBSZENE_PFADINFO_,

		_GUI_ID_LISTBOX_SUBSZENEN_,

		_GUI_ID_BUTTON_NEU_SUBSZENE_,
		_GUI_ID_BUTTON_UEBERNEHMEN_SUBSZENE_,
		_GUI_ID_BUTTON_LOESCHEN_SUBSZENE_,

		_GUI_ID_FILEOPENDIALOG_SUBSZENE_,

		// Erstellung
		_GUI_ID_CHECKBOX_ERSTELLUNG_FRAKTALZEICHENANWEISUNG_,
		_GUI_ID_CHECKBOX_ERSTELLUNG_VOXELZEICHNEN_EROSION_,
		_GUI_ID_CHECKBOX_ERSTELLUNG_FILTERUNG1_,
		_GUI_ID_CHECKBOX_ERSTELLUNG_ARCHITEKT_,
		_GUI_ID_CHECKBOX_ERSTELLUNG_FILTERUNG2_,
		_GUI_ID_CHECKBOX_ERSTELLUNG_UMWANDLUNGVOXEL_,
		_GUI_ID_BUTTON_ERSTELLE_DUNGEON_,
		_GUI_ID_BUTTON_ZEIGE_DUNGEON_,

		// Weiteres
		_GUI_ID_EDITBOX_ALLGEMEIN_ZUFALLSPARAMETER_A_,
		_GUI_ID_EDITBOX_ALLGEMEIN_ZUFALLSPARAMETER_C_,
		_GUI_ID_EDITBOX_ALLGEMEIN_ZUFALLSPARAMETER_M_,

		_GUI_ID_EDITBOX_FARBE_HOEHLE_R_,
		_GUI_ID_EDITBOX_FARBE_HOEHLE_G_,
		_GUI_ID_EDITBOX_FARBE_HOEHLE_B_,

		_GUI_ID_EDITBOX_FARBE_HINTERGRUND_R_,
		_GUI_ID_EDITBOX_FARBE_HINTERGRUND_G_,
		_GUI_ID_EDITBOX_FARBE_HINTERGRUND_B_,

		_GUI_ID_BUTTON_FARBE_HOEHLE_UEBERNEHMEN_,
		_GUI_ID_BUTTON_FARBE_HINTERGRUND_UEBERNEHMEN_,
		_GUI_ID_BUTTON_MESHCACHE_TEXTUREBUFFER_LOESCHEN_
	};

	// GUI-Klasse
	class CGUI
	{
	public:
		CGUI(irr::gui::IGUIEnvironment* _GUIEnvironment);

		void ErstelleMenue();
		void ErstelleFenster_Dateizugriff_Einstellungen();
		void ErstelleFenster_Dateizugriff_Ergebnisse();
		void ErstelleFenster_FraktalEditor();
		void ErstelleFenster_VoxelHoehle();
		void ErstelleFenster_Gaenge();
		void ErstelleFenster_Architekt();
		void ErstelleFenster_Erstellung();
		void ErstelleFenster_Weiteres();
		
		void ErstelleFenster_FileOpenDialog(irr::s32 _ID, bool _Speichern);

		void LoescheGUI();

		// GUI-Umgebung
		irr::gui::IGUIEnvironment* GUIEnvironment;

	private:
		// Zeiger auf andere Objekte

	};
	
} // END NAMESPACE DunGen

#endif